#!/usr/bin/env ruby
#-*- coding: utf-8 -*-

require_relative 'lib/game'

using Dice

player = CLIPlayerCharacter.new 'Everton', ht: 12, st: 3.d6
player.have :regeneration

enemy1 = NonPlayerCharacter.new 'Orc 1'
enemy2 = NonPlayerCharacter.new 'Orc 2'

game   = Game.new
game.characters << player
game.characters << enemy1
game.characters << enemy2

winner = game.run!
puts "Winner: #{winner}"
